(ns mail-xls-sheets-clj.excel)

;; (import 'org.apache.poi.xssf.usermodel.XSSFWorkbook)
;; (XSSFWorkbook.)
;; (def w (XSSFWorkbook.))
;; (def fis (java.io.FileInputStream. (java.io.File. "/tmp/analytics.xlsx")))
;; (def w (XSSFWorkbook. fis))
;; (.getSheetAt w 0)
;; (def s (.getSheetAt w 0))
;; (def i (.iterator sheet))
;; (def i (.iterator s))
;; (.next i)
;; (def i (.iterator s))
;; (.next i)
;; (def r *1)
;; (.cellIterator r)
;; (def ci (.cellIterator r))
;; (.next ci)
;; (def r (.next i))
;; (def ci (.cellIterator r))
;; (def r (.next i))
;; (.next ci)
;; (def r (.next i))
;; (.next ci)
;; (def ci (.cellIterator r))
;; (.next ci)
;; (def r (.next i))
;; (def ci (.cellIterator r))
;; (.next ci)
